language: python
env:
  - DB=mysql
  - DB=postgresql
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
    - mysql
    - postgresql
before_install:
  - if [[ $DB = 'mysql' ]]; then pip install mysqlclient; fi
before_script:
  - if [[ $DB = 'postgresql' ]]; then psql -c 'create database pydnd;' -U postgres; fi
  - if [[ $DB = 'postgresql' ]]; then psql -c 'create role pydnd with createdb login;' -U postgres; fi
  - if [[ $DB = 'mysql' ]]; then mysql -e 'CREATE DATABASE pydnd;'; fi
  - if [[ $DB = 'mysql' ]]; then mysql -e "CREATE USER pydnd@localhost IDENTIFIED BY 'pydnd';"; fi
  - if [[ $DB = 'mysql' ]]; then mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'pydnd'@'localhost'"; fi
  - if [[ $DB = 'mysql' ]]; then mysql -u root -e "FLUSH PRIVILEGES;"; fi

  - python ./manage.py makemigrations --noinput
  - python ./manage.py migrate --noinput
  - python ./manage.py loaddata */fixtures/*.json
script: ./runtests
after_success:
    coveralls --data_file .coverage
