#!/bin/bash

dropdb pydnd
createdb pydnd
/bin/rm */migrations/0*.py
./manage.py makemigrations
./manage.py migrate
./manage.py loaddata */fixtures/*.json
# ./manage.py createsuperuser --username admin --email maybe@yes.no

