#!/bin/sh
  
export PYTHONPATH=pydnd
TEST="./manage.py test --settings pydnd.settings"
coverage run --include 'encounter/*,lib/*,character/*,equipment/*,monster/*,message/*,world/*' ${TEST} && coverage report -m

#EOF
