# Generated by Django 2.0 on 2017-12-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('I', 'Item'), ('W', 'Weapon'), ('A', 'Armour')], default='I', max_length=1)),
                ('cost', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('magic', models.CharField(blank=True, default='', max_length=10)),
                ('damage', models.CharField(default='', max_length=10)),
                ('reach', models.IntegerField(default=0)),
                ('ac_base', models.IntegerField(default=10)),
                ('ac_modifier', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
            },
        ),
    ]
