# Generated by Django 2.0.1 on 2018-03-06 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=20)),
                ('weight', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Equipment',
            },
        ),
        migrations.CreateModel(
            name='Armour',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipment.Equipment')),
                ('stealth_disadv', models.BooleanField(default=False)),
                ('base_ac', models.IntegerField(default=-1)),
                ('armour_categ', models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('H', 'Heavy')], max_length=1)),
            ],
            bases=('equipment.equipment',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipment.Equipment')),
                ('damage', models.CharField(max_length=10)),
                ('damage_cat', models.CharField(choices=[('B', 'Bludgeoning'), ('S', 'Slashing'), ('P', 'Piercing')], max_length=2)),
                ('properties', models.CharField(max_length=50)),
                ('normal_range', models.IntegerField(default=0)),
                ('long_range', models.IntegerField(default=0)),
            ],
            bases=('equipment.equipment',),
        ),
    ]
