# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-21 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='damage',
            field=models.CharField(max_length=50),
        ),
    ]
