# Generated by Django 2.0 on 2017-12-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='ac',
            field=models.IntegerField(default=10, verbose_name='AC'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='thaco',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='monster',
            name='treasure',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
