# Generated by Django 2.0 on 2017-12-12 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0002_auto_20171212_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monsterstate',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='encounter.Encounter'),
        ),
        migrations.AlterField(
            model_name='monsterstate',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monster.Monster'),
        ),
    ]
