# Generated by Django 2.0.2 on 2018-03-13 09:51

from django.db import migrations, models
import django.db.models.deletion
import gm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('charclass', models.CharField(choices=[('BB', 'Barbarian'), ('BD', 'Bard'), ('CL', 'Cleric'), ('DR', 'Druid'), ('FG', 'Fighter'), ('MK', 'Monk'), ('PL', 'Paladin'), ('RA', 'Ranger'), ('RO', 'Rogue'), ('SO', 'Sorceror'), ('WA', 'Warlock'), ('WZ', 'Wizard')], max_length=5)),
                ('race', models.CharField(choices=[('HU', 'Human'), ('EL', 'Elf'), ('DW', 'Dwarf'), ('HE', 'Half Elven'), ('HL', 'Halfling'), ('GN', 'Gnome')], default='HU', max_length=3)),
                ('subrace', models.CharField(choices=[('HU', 'Human'), ('EL', 'Elf'), ('DW', 'Dwarf'), ('HE', 'Half Elven'), ('HL', 'Halfling'), ('GN', 'Gnome')], default='N', max_length=3)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U', max_length=1)),
                ('hp', models.IntegerField(default=0)),
                ('max_hp', models.IntegerField(default=0)),
                ('ac', models.IntegerField(default=10)),
                ('dmg', models.IntegerField(default=1)),
                ('encumbrance', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=30)),
                ('xp', models.IntegerField(default=0)),
                ('align', models.CharField(choices=[('LG', 'Lawful Good'), ('LN', 'Lawful Neutral'), ('LE', 'Lawful Evil'), ('NG', 'Neutral Good'), ('N', 'True Neutral'), ('NE', 'Neutral Evil'), ('CG', 'Chaotic Good'), ('CN', 'Chaotic Neutral'), ('CE', 'Chaotic Evil'), ('U', 'Unaligned')], default='N', max_length=2)),
                ('level', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('XX', 'XX'), ('OK', 'OK'), ('DE', 'Dead'), ('UC', 'Unconscious')], default='XX', max_length=2)),
                ('proficiency', models.IntegerField(default=-1)),
                ('x', models.IntegerField(default=-1)),
                ('y', models.IntegerField(default=-1)),
                ('stat_str', models.IntegerField(default=-1)),
                ('stat_int', models.IntegerField(default=-1)),
                ('stat_wis', models.IntegerField(default=-1)),
                ('stat_dex', models.IntegerField(default=-1)),
                ('stat_con', models.IntegerField(default=-1)),
                ('stat_cha', models.IntegerField(default=-1)),
                ('plat', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('silver', models.IntegerField(default=0)),
                ('copper', models.IntegerField(default=0)),
                ('moves', models.IntegerField(default=-1)),
                ('attacks', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='EquipState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('ready', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Character')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('charclass', models.CharField(choices=[('M', 'Mage'), ('C', 'Cleric')], max_length=5)),
                ('spellfile', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SpellState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepared', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Character')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.Spell')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='gear',
            field=gm2m.fields.GM2MField(through='character.EquipState', through_fields=['character', 'content_object', 'content_type', 'object_id']),
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(blank=True, through='character.SpellState', to='character.Spell'),
        ),
        migrations.AddField(
            model_name='character',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.World'),
        ),
    ]
