# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armour',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.Equipment')),
                ('bonus', models.IntegerField()),
                ('magic', models.IntegerField()),
            ],
            bases=('character.equipment',),
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='character.Equipment')),
                ('damage', models.CharField(max_length=10)),
                ('magic', models.IntegerField()),
            ],
            bases=('character.equipment',),
        ),
    ]
