# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-13 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_armour_weapons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armour',
            name='magic',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='magic',
            field=models.IntegerField(default=0),
        ),
    ]
