# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-14 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_auto_20171113_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armour',
            name='bonus',
        ),
        migrations.AddField(
            model_name='armour',
            name='ac_base',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='armour',
            name='ac_modifier',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='armour',
            name='magic',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='magic',
            field=models.CharField(default='', max_length=10),
        ),
    ]
